import { BtnCreatePost } from "@/components/Button/BtnCreatePost";
import { PubSidebar } from "@/components/pubsidebar/PubSidebar";
import { SearchBar } from "@/components/Search/SearchBar";
import { Sidebar } from "@/components/sidebar/Sidebar";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex min-h-screen px-5 " + inter.className} data-theme='night'>
        <SessionProvider>
          <Sidebar />
          <section className="flex p-3 w-full">
            <div className="w-full">
            <div className="flex items-center justify-around">
              <SearchBar />
              <BtnCreatePost />
            </div>
              {children}
            </div>
          </section>
          <PubSidebar />
        </SessionProvider>
        </body>
    </html>
  );
}
