import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { SessionProvider } from "next-auth/react";
import { PubSidebar } from "@/components/pubsidebar/PubSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"flex min-h-screen px-5 " + inter.className} data-theme='night'>
        <SessionProvider>
          <Sidebar />
          {children}
          <PubSidebar />
        </SessionProvider>
        </body>
    </html>
  );
}
